### ISSUE TITLE
[POTENTIAL BUG] When scanning a QR by upload, the QR camera stays on the QR & infinite loop

### ISSUE THREAD

**Issue by sophiacabungcal** [CMPUT301F24throat/throat-events#154]
Upload a QR to scan, scan it to get redirected to event details where you can join waiting list
If you try to press 'Back' the user is redirected to QR Camera page again which redirects you back to event details (infinite loop)

**Comment by Cole-Mckay** [comment]
You just need to quickly look away after pressing back. There isn't a loop, the camera is just positioned to scan the QR and scans it again.
